#!/usr/bin/env python3
"""SDD Doctor — init / fix mode.

Usage:
    python3 .claude/skills/sdd-doctor/init.py            # init all missing
    python3 .claude/skills/sdd-doctor/init.py --fix 3 6   # fix specific checks
    python3 .claude/skills/sdd-doctor/init.py --dry-run

This script assumes bootstrap.sh has already copied the template files into
.claude/. init.py does NOT fetch files over the network — it only:

1. Regenerates `.claude/capabilities.md` via auto-detect of installed plugins.
2. Updates `.claude/settings.json` to match the detected stack.
3. Preserves every section marked `<!-- user-override -->`.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
from typing import Any

# Reuse check logic
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from check import detect_stack, run_all_checks  # noqa: E402

USER_OVERRIDE_MARKER = "<!-- user-override -->"


# ────────────────────────────────────────────────────────────────────────────
# Capability registry generation
# ────────────────────────────────────────────────────────────────────────────


def scan_plugin_capabilities() -> dict[str, list[dict[str, str]]]:
    """Scans ~/.claude/plugins/cache/ for skills and agents."""
    plugins_dir = pathlib.Path.home() / ".claude" / "plugins" / "cache"
    result: dict[str, list[dict[str, str]]] = {"agents": [], "skills": []}
    if not plugins_dir.exists():
        return result

    for plugin in plugins_dir.iterdir():
        if not plugin.is_dir():
            continue
        plugin_name = plugin.name
        # Agents
        for agent_dir in plugin.rglob("agents"):
            if not agent_dir.is_dir():
                continue
            for agent_file in agent_dir.glob("*.md"):
                frontmatter = _parse_frontmatter(agent_file.read_text(encoding="utf-8"))
                result["agents"].append(
                    {
                        "name": frontmatter.get("name", agent_file.stem),
                        "description": frontmatter.get("description", "")[:200],
                        "plugin": plugin_name,
                    }
                )
        # Skills
        for skill_md in plugin.rglob("SKILL.md"):
            frontmatter = _parse_frontmatter(skill_md.read_text(encoding="utf-8"))
            result["skills"].append(
                {
                    "name": frontmatter.get("name", skill_md.parent.name),
                    "description": frontmatter.get("description", "")[:200],
                    "plugin": plugin_name,
                }
            )
    return result


def _parse_frontmatter(text: str) -> dict[str, str]:
    """Very simple YAML frontmatter parser (name + description)."""
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    fm_text = text[3:end]
    out: dict[str, str] = {}
    current_key: str | None = None
    for line in fm_text.splitlines():
        if not line.strip():
            continue
        if ":" in line and not line.startswith(" "):
            key, _, val = line.partition(":")
            out[key.strip()] = val.strip().strip('"').strip("'")
            current_key = key.strip()
        elif current_key and line.startswith(" "):
            # Continuation
            out[current_key] = (out[current_key] + " " + line.strip()).strip()
    return out


def generate_capabilities_md(root: pathlib.Path) -> str:
    """Generates the content of .claude/capabilities.md via auto-detection.

    Preserves every section marked <!-- user-override --> from the existing file.
    """
    stack = detect_stack(root)
    caps = scan_plugin_capabilities()

    # Auto-generated sections
    auto = []
    auto.append("# Project Capabilities\n")
    auto.append("> Auto-generated by `/sdd-doctor init`. Sections marked")
    auto.append("> `<!-- user-override -->` are preserved on re-init.\n")

    # Specialist agents
    auto.append("## Specialist agents (delegate implementation work)\n")
    auto.append("<!-- auto-generated -->")
    if caps["agents"]:
        for a in sorted(caps["agents"], key=lambda x: x["name"]):
            auto.append(f"- **{a['name']}** ({a['plugin']}) — {a['description']}")
    else:
        auto.append("- _(no specialist agents — install a plugin marketplace)_")
    auto.append("")

    # Skills
    auto.append("## Skills (load into context on demand)\n")
    auto.append("<!-- auto-generated -->")
    if caps["skills"]:
        for s in sorted(caps["skills"], key=lambda x: x["name"]):
            auto.append(f"- `{s['name']}` ({s['plugin']}) — {s['description']}")
    else:
        auto.append("- _(no skills — install a plugin marketplace)_")
    auto.append("")

    # Stack profile
    auto.append("## Stack profile\n")
    auto.append("<!-- auto-generated -->")
    for k, v in stack.items():
        auto.append(f"- **{k}**: {v}")
    auto.append("")

    auto_text = "\n".join(auto)

    # Default routing rules (user-override-able)
    routing_default = """## Task type → routing rules

<!-- user-override -->
| Task type           | Specialist agent          | Skills to load                          |
|---------------------|---------------------------|-----------------------------------------|
| ui-contract         | (orchestrator)            | design-system                           |
| ui-component-test   | storybook-tester          | storybook-testing, design-system        |
| ui-component        | (orchestrator)            | design-system                           |
| server-action       | nextjs-backend-engineer   | server-actions, error-handling          |
| route-handler       | nextjs-backend-engineer   | server-actions, structured-logging      |
| unit-test           | (orchestrator)            | unit-testing                            |
| e2e-test            | (orchestrator)            | playwright-cli                          |
| a11y-audit          | (orchestrator)            | accessibility-audit                     |
| test-strategy       | testing-strategist        | unit-testing, playwright-cli            |
| refactor            | (orchestrator)            | react-doctor (post)                     |
| generic             | (orchestrator)            | —                                       |

## Custom routing rules

<!-- user-override -->
<!-- Add your own task types and routing rules. /tasks uses these alongside the defaults above. -->
"""

    # Merge with existing user-override sections
    existing_path = root / ".claude" / "capabilities.md"
    if existing_path.exists():
        existing = existing_path.read_text(encoding="utf-8")
        preserved = _extract_user_override_sections(existing)
        if preserved:
            # Replace default user-override sections with the preserved versions
            for section_title, section_content in preserved.items():
                pattern = re.compile(
                    rf"^## {re.escape(section_title)}\s*\n\n<!-- user-override -->.*?(?=^## |\Z)",
                    re.MULTILINE | re.DOTALL,
                )
                if pattern.search(routing_default):
                    routing_default = pattern.sub(section_content, routing_default)
                else:
                    routing_default += "\n" + section_content

    return auto_text + "\n" + routing_default


def _extract_user_override_sections(text: str) -> dict[str, str]:
    """Extracts sections marked <!-- user-override --> from capabilities.md."""
    sections: dict[str, str] = {}
    pattern = re.compile(
        r"^(## (.+?))\s*\n\n<!-- user-override -->\n(.*?)(?=^## |\Z)",
        re.MULTILINE | re.DOTALL,
    )
    for match in pattern.finditer(text):
        title = match.group(2).strip()
        body = match.group(0)
        sections[title] = body.rstrip() + "\n"
    return sections


# ────────────────────────────────────────────────────────────────────────────
# Settings.json: stack-aware hooks
# ────────────────────────────────────────────────────────────────────────────


def update_settings(root: pathlib.Path) -> None:
    settings_path = root / ".claude" / "settings.json"
    if not settings_path.exists():
        # Bootstrap has already copied a default — nothing to do
        return
    try:
        data = json.loads(settings_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        data = {}

    data.setdefault("hooks", {})
    data["hooks"]["PostToolUse"] = [
        {
            "matcher": "Edit|Write|MultiEdit",
            "hooks": [
                {"type": "command", "command": "python3 .claude/hooks/typecheck.py"},
                {"type": "command", "command": "bash .claude/hooks/lint.sh"},
            ],
        }
    ]
    settings_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


# ────────────────────────────────────────────────────────────────────────────
# Main
# ────────────────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".", help="Project root")
    parser.add_argument(
        "--fix",
        nargs="*",
        type=int,
        help="Fix only the specified check IDs (1-10). Omit to init everything.",
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    root = pathlib.Path(args.root).resolve()
    print(f"📁 Project root: {root}")

    # Always regenerate capabilities (idempotent + preserves user-overrides)
    caps_path = root / ".claude" / "capabilities.md"
    caps_content = generate_capabilities_md(root)
    if args.dry_run:
        print("--- capabilities.md (dry-run) ---")
        print(caps_content[:500] + "...")
    else:
        caps_path.parent.mkdir(parents=True, exist_ok=True)
        caps_path.write_text(caps_content, encoding="utf-8")
        print(f"✓ {caps_path.relative_to(root)} regenerated")

    if not args.dry_run:
        update_settings(root)
        print("✓ .claude/settings.json hooks updated")

    # Final check
    report = run_all_checks(root)
    print(f"\nFinal status: {report['status']}")
    return 0  # init always exits 0


if __name__ == "__main__":
    sys.exit(main())
